version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_logitrack
    environment:
      POSTGRES_USER: logitrack
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: logitrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
